services:
  web:
    build: .
    container_name: recomed_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:17
    container_name: recomed_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/db/docker:/docker-entrypoint-initdb.d
  
  seed:
    build: .
    depends_on:
      - db
    entrypoint: ["python", "app/utils/seed_holidays.py"]
    volumes:
      - .:/app
    env_file:
      - .env

  test_short:
    build: .
    command: ["pytest", "tests/", "--disable-warnings", "--tb-short"]
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app

  test:
    build: .
    command: ["pytest", "tests/", "-v", "--disable-warnings"]
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  postgres_data: